service: minfos-beer-fridge

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2
  apiKeys:
    - name: mbf-device
      value: ${ssm:/MinfosBeerFridge/ApiKeys/Client}
      description: "For use by the MBF hardware for posting temperature data"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: 'arn:aws:dynamodb:ap-southeast-2:*:*'

functions:
  submitTemperatures:
    handler: handler.submitTemperatures
    events:
      - http:
          path: temperature
          method: post
          private: true

resources:
  Resources:
    usersTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MBF5
        AttributeDefinitions:
          - AttributeName: Date
            AttributeType: S
          - AttributeName: TimeStamp
            AttributeType: S
        KeySchema:
          - AttributeName: Date
            KeyType: HASH
          - AttributeName: TimeStamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
