service: minfos-beer-fridge

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2
  apiKeys:
    - name: mbf-device
      value: ${ssm:/MinfosBeerFridge/ApiKeys/Client}
      description: "For use by the MBF hardware for posting temperature data"

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

functions:
  submitTemperatures:
    handler: handler.submitTemperatures
    events:
      - http:
          path: temperature
          method: post
          private: true
#    Define function environment variables here
#    environment:
#      variable2: value2
